baseURL                   = "/"
publishDir = "."
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


theme = "AllinOne"
title                      = "Arthur Rocha"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "/content/post"  

  [[menu.main]]
    name                   = "About"
    weight                 = -110
    identifier             = "about"
    url                    = "/content/about" 

  [[menu.main]]
    name                   = "Projects"
    weight                 = -100
    identifier             = "projects"
    url                    = "/content/projects"  

  
  [[menu.main]]
    name                   = "Contact"
    weight                 = -90
    identifier             = "moment"
    url                    = "/content/moment" 

 

[params]
  #faviconfile              = "img/zheng.png"               # from static/
  avatar                   = "img/Alpha.jpeg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Arthur Rocha"
  description              = ["Statistician.", "Data scientist.", "In love with R & data visualization."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello! Welcome to my site!"
  welcome_word             = " 'It is not a question of if but how' "

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "arthurcesariv@gmail.com"
  github                   = "//github.com/arthur-rocha"
  linkedin                 = "//linkedin.com/in/arthur-cesar-rocha"

  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  #googleAnalytics          = "your-google-analytic-id"
    
    
