---
title: "How many rounds on top are necessary to be a soccer champion?"
author: "Arthur Rocha"
date: "2019-04-24T12:03:06-03:00"
categories:
  - Cool stuff
tags:
  - R
  - soccer
  - brazil
  - statistics
  - ROC
  - logistic-regression
output: html_document
---



<div id="introduction" class="section level2">
<h2>Introduction</h2>
<ul>
<li>Like almost everyone here in Brazil, I have a passion for football (or soccer) and because of that my father and I are always alert to the national championship.<br />
So, a few days ago my father gave me a challenge, he challenged me to understand what is needed to be a champion in the brazilian national soccer league (knowed here as “Brasileirão”) since the competition change its format to a point based championship in 2003.</li>
</ul>
<p>Thus I’ve accepted the challenge and here are the results:</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<ul>
<li>Firstly we need to get the data!!</li>
</ul>
<p>I haven’t found a well structured data base to work with, so I had to work with the information provided by this <a href="http://futpedia.globo.com/campeonato/campeonato-brasileiro/">site</a> and
I had to do a function to scrap the data.</p>
<ul>
<li>Packages used</li>
</ul>
<pre class="r"><code>library(XML)      #Package to do web scraping
library(dplyr)    #Manipulation
library(magrittr) #Manipulation
library(tidyr)    #Manipulation
library(scales)   #Formatting
library(ggplot2)  #Plots
library(pROC)     #ROC curves</code></pre>
<ul>
<li>That is the function to do the web scraping. Note that the site has information only until 2015.</li>
</ul>
<pre class="r"><code># URL base to all years
url1=&quot;futpedia.globo.com/campeonato
/campeonato-brasileiro/&quot;

#Empty data frame to store the information
games= data_frame()

for (i in 2003:2015) { ## years
  url2 = paste0(url1,i)
  
  readHTMLTable(url2,as.data.frame = T)%&gt;%
    data.table::rbindlist()%&gt;%
    setNames(c(&quot;Position&quot;,&quot;Team&quot;,&quot;Points&quot;,&quot;Games&quot;,&quot;Victories&quot;,&quot;Ties&quot;,
               &quot;Losses&quot;,&quot;Goals scored&quot;,&quot;Goals conceded&quot;,&quot;Goal difference&quot;,
               &quot;Performance&quot;))%&gt;%
    mutate(Year = i)%&gt;%
    bind_rows(games) -&gt; games
}</code></pre>
<p>If you don’t want to scrap the data (because it can take some time and sometimes doesn’t work so fine) you can get it from here <a href="https://github.com/arthur-rocha/Brasileirao/raw/master/Brasileirao%202003%20-%202015.csv">Data!</a>.</p>
<p><strong>Tip:</strong> Be aware with the encoding! (use “latin-1”)</p>
<ul>
<li>Moving on, we need some extra information, like which team was the champion in the season and how many games (rounds) are in each season, because the number of teams has changed in 2005 and changed again in 2006.</li>
</ul>
<pre class="r"><code># Champions data
champ_dt = data_frame(Year = 2003:2018,
                      Champion = c(&quot;Cruzeiro&quot;,&quot;Santos&quot;,&quot;Corinthians&quot;,&quot;São Paulo&quot;,
                                   &quot;São Paulo&quot;,&quot;São Paulo&quot;,&quot;Flamengo&quot;,&quot;Fluminense&quot;,
                                   &quot;Corinthians&quot;,&quot;Fluminense&quot;,&quot;Cruzeiro&quot;,&quot;Cruzeiro&quot;,
                                   &quot;Corinthians&quot;,&quot;Palmeiras&quot;,&quot;Corinthias&quot;,&quot;Palmeiras&quot;))</code></pre>
<pre class="r"><code>games %&lt;&gt;%  # Tracking the round (game) number
  mutate(Round = c(rep(rep(1:38,each =20),10),
                   rep(1:42,each =22),
                   rep(1:46,each =24),rep(1:46,each =24)))%&gt;%
  
  # Finding the champion in each season
  inner_join(champ_dt) %&gt;%
  # Is this team the champion of this year?
  mutate(Champ = if_else(Team == Champion, 1,0),
         # Total number of games in the season
         N_round = case_when(Year &lt; 2005 ~ 46,
                             Year == 2005 ~ 42,
                             Year &gt; 2005 ~38),
         # In this round, this team is in the first place?
         First_place = if_else(Position ==1,1,0 ),
         # In this round, this team is in the first place
         # and is the champion?
         TP = if_else(First_place == 1 &amp; Champ == 1,
                      1,0),
         # In this round, this team is in the first place
         # and isn&#39;t the champion?
         TN = if_else(First_place == 1 &amp; Champ == 1,
                      1,0))</code></pre>
<ul>
<li>Let’s take a look in the data</li>
</ul>
<pre class="r"><code>head(games)</code></pre>
<pre><code>##   Position         Team Points Games Victories Ties Losses Goals scored
## 1        1        Sport      3     1         1    0      0            4
## 2        2 Athletico-PR      3     1         1    0      0            3
## 3        3  Chapecoense      3     1         1    0      0            2
## 4        3    São Paulo      3     1         1    0      0            2
## 5        5  Corinthians      3     1         1    0      0            1
## 6        6   Fluminense      3     1         1    0      0            1
##   Goals conceded Goal difference Performance Year Round    Champion Champ
## 1              1               3         100 2015     1 Corinthians     0
## 2              0               3         100 2015     1 Corinthians     0
## 3              1               1         100 2015     1 Corinthians     0
## 4              1               1         100 2015     1 Corinthians     0
## 5              0               1         100 2015     1 Corinthians     1
## 6              0               1         100 2015     1 Corinthians     0
##   N_round First_place TP TN
## 1      38           1  0  0
## 2      38           0  0  0
## 3      38           0  0  0
## 4      38           0  0  0
## 5      38           0  0  0
## 6      38           0  0  0</code></pre>
<p>All seems ok, let’s continue…</p>
</div>
<div id="analysing-the-initial-rounds." class="section level2">
<h2>Analysing the initial rounds.</h2>
<ul>
<li>So, now we can analyse the data. Initially, we can try to find the “champion profile” at the 5th and 10th round.</li>
</ul>
<div id="th-round" class="section level3">
<h3>5th round:</h3>
<pre class="r"><code># Making a plot
games %&gt;%
  filter(Round == 5)%&gt;%
  select(Points, Victories, Ties, Losses,
         `Goals scored`, `Goals conceded`,
         Position,Champ)%&gt;%
  mutate_all(.funs = as.numeric)%&gt;%
  mutate(Champ = factor(Champ, labels= c(&quot;Not champion&quot;,&quot;Champion&quot;)))%&gt;%
  gather(key=&quot;Variable&quot;,value=&quot;value&quot;,-c(Champ))%&gt;%
  ggplot(aes(value,fill=Champ))+
  geom_histogram(aes(y=..density..),binwidth = 1,col=1,alpha=.3)+
  facet_wrap( ~Variable,scales = &quot;free&quot;)+
  theme_light()+
  scale_fill_discrete(&quot;&quot;)+
  ylab(&quot;Frequency (%)&quot;)+
  scale_y_continuous(labels = scales::percent)</code></pre>
<p><img src="/post/2019-04-24-how-many-rounds-on-top-to-glory_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<ul>
<li>Note that are negative points, this happened because of punishments gave by CBF for some teams.</li>
</ul>
<pre class="r"><code># Making a table
games %&gt;%
  filter(Round == 5)%&gt;%
  select(Points, Victories, Ties, Losses,
         `Goals scored`, `Goals conceded`,
         Position,Champ,Performance)%&gt;%
  mutate_all(.funs = as.numeric)%&gt;%
  mutate(Champ = factor(Champ, labels= c(&quot;Not champion&quot;,&quot;Champion&quot;)))%&gt;%
  gather(key=&quot;Variable&quot;,value=&quot;value&quot;,-c(Champ))%&gt;%
  group_by(Variable,Champ)%&gt;%
  summarise(Min= min(value),
            Mean = mean(value) %&gt;% round(digits = 2),
            Max = max(value),
            SD = sd(value) %&gt;% round(digits = 2))%&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">Champ</th>
<th align="right">Min</th>
<th align="right">Mean</th>
<th align="right">Max</th>
<th align="right">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Goals conceded</td>
<td align="left">Not champion</td>
<td align="right">1</td>
<td align="right">6.59</td>
<td align="right">17.0</td>
<td align="right">2.95</td>
</tr>
<tr class="even">
<td align="left">Goals conceded</td>
<td align="left">Champion</td>
<td align="right">2</td>
<td align="right">6.00</td>
<td align="right">12.0</td>
<td align="right">2.83</td>
</tr>
<tr class="odd">
<td align="left">Goals scored</td>
<td align="left">Not champion</td>
<td align="right">1</td>
<td align="right">6.49</td>
<td align="right">16.0</td>
<td align="right">2.71</td>
</tr>
<tr class="even">
<td align="left">Goals scored</td>
<td align="left">Champion</td>
<td align="right">3</td>
<td align="right">7.92</td>
<td align="right">17.0</td>
<td align="right">3.59</td>
</tr>
<tr class="odd">
<td align="left">Losses</td>
<td align="left">Not champion</td>
<td align="right">0</td>
<td align="right">1.77</td>
<td align="right">5.0</td>
<td align="right">1.10</td>
</tr>
<tr class="even">
<td align="left">Losses</td>
<td align="left">Champion</td>
<td align="right">0</td>
<td align="right">1.38</td>
<td align="right">3.0</td>
<td align="right">0.96</td>
</tr>
<tr class="odd">
<td align="left">Performance</td>
<td align="left">Not champion</td>
<td align="right">0</td>
<td align="right">44.44</td>
<td align="right">100.0</td>
<td align="right">19.67</td>
</tr>
<tr class="even">
<td align="left">Performance</td>
<td align="left">Champion</td>
<td align="right">40</td>
<td align="right">55.91</td>
<td align="right">86.7</td>
<td align="right">13.75</td>
</tr>
<tr class="odd">
<td align="left">Points</td>
<td align="left">Not champion</td>
<td align="right">-13</td>
<td align="right">6.57</td>
<td align="right">15.0</td>
<td align="right">3.26</td>
</tr>
<tr class="even">
<td align="left">Points</td>
<td align="left">Champion</td>
<td align="right">6</td>
<td align="right">8.38</td>
<td align="right">13.0</td>
<td align="right">2.06</td>
</tr>
<tr class="odd">
<td align="left">Position</td>
<td align="left">Not champion</td>
<td align="right">1</td>
<td align="right">11.11</td>
<td align="right">24.0</td>
<td align="right">6.11</td>
</tr>
<tr class="even">
<td align="left">Position</td>
<td align="left">Champion</td>
<td align="right">1</td>
<td align="right">7.23</td>
<td align="right">15.0</td>
<td align="right">4.40</td>
</tr>
<tr class="odd">
<td align="left">Ties</td>
<td align="left">Not champion</td>
<td align="right">0</td>
<td align="right">1.52</td>
<td align="right">4.0</td>
<td align="right">0.96</td>
</tr>
<tr class="even">
<td align="left">Ties</td>
<td align="left">Champion</td>
<td align="right">0</td>
<td align="right">1.23</td>
<td align="right">3.0</td>
<td align="right">1.01</td>
</tr>
<tr class="odd">
<td align="left">Victories</td>
<td align="left">Not champion</td>
<td align="right">0</td>
<td align="right">1.72</td>
<td align="right">5.0</td>
<td align="right">1.07</td>
</tr>
<tr class="even">
<td align="left">Victories</td>
<td align="left">Champion</td>
<td align="right">1</td>
<td align="right">2.38</td>
<td align="right">4.0</td>
<td align="right">0.77</td>
</tr>
</tbody>
</table>
<p>Here we can see that, at the 5th round, all the champions have woned at least one game, and drawn three games at the most, with the minimum performance (points made / possible points) of 40%, but none of the champions had a performance score of 100% at the 5th round.</p>
<p>The minimum number of goals scored by the champions was 3 and the maximum number of goals conceded was 12.</p>
</div>
<div id="th-round-1" class="section level3">
<h3>10th round:</h3>
<pre class="r"><code># Making a plot
games %&gt;%
  filter(Round == 10)%&gt;%
  select(Points, Victories, Ties, Losses,
         `Goals scored`, `Goals conceded`,
         Position,Champ)%&gt;%
  mutate_all(.funs = as.numeric)%&gt;%
  mutate(Champ = factor(Champ, labels= c(&quot;Not champion&quot;,&quot;Champion&quot;)))%&gt;%
  gather(key=&quot;Variable&quot;,value=&quot;value&quot;,-c(Champ))%&gt;%
  mutate(y = if_else(Champ==&quot;Champion&quot;, value/13,value/ 270 ))%&gt;%
  ggplot(aes(value,fill=Champ))+
  #geom_point()+
  geom_histogram(aes(y=..density..),binwidth = 1,col=1,alpha=.3)+
  facet_wrap( ~Variable,scales = &quot;free&quot;)+
  theme_light()+
  scale_fill_discrete(&quot;&quot;)+
  ylab(&quot;Frequency (%)&quot;)+
  scale_y_continuous(labels = scales::percent)+
  scale_x_continuous(breaks = seq(0,30,by=4))</code></pre>
<p><img src="/post/2019-04-24-how-many-rounds-on-top-to-glory_files/figure-html/unnamed-chunk-9-1.png" width="672" />
- Note that are negative points again, this happened because of the same reason.</p>
<pre class="r"><code># Making a table
games %&gt;%
  filter(Round == 10)%&gt;%
  select(Points, Victories, Ties, Losses,
         `Goals scored`, `Goals conceded`,
         Position,Champ,Performance)%&gt;%
  mutate_all(.funs = as.numeric)%&gt;%
  mutate(Champ = factor(Champ, labels= c(&quot;Not champion&quot;,&quot;Champion&quot;)))%&gt;%
  gather(key=&quot;Variable&quot;,value=&quot;value&quot;,-c(Champ))%&gt;%
  group_by(Variable,Champ)%&gt;%
  summarise(Min= min(value),
            Mean = mean(value) %&gt;% round(digits = 2),
            Max = max(value),
            SD = sd(value)%&gt;% round(digits = 2))%&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">Champ</th>
<th align="right">Min</th>
<th align="right">Mean</th>
<th align="right">Max</th>
<th align="right">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Goals conceded</td>
<td align="left">Not champion</td>
<td align="right">4.0</td>
<td align="right">13.30</td>
<td align="right">26.0</td>
<td align="right">3.89</td>
</tr>
<tr class="even">
<td align="left">Goals conceded</td>
<td align="left">Champion</td>
<td align="right">3.0</td>
<td align="right">10.15</td>
<td align="right">19.0</td>
<td align="right">5.19</td>
</tr>
<tr class="odd">
<td align="left">Goals scored</td>
<td align="left">Not champion</td>
<td align="right">3.0</td>
<td align="right">12.95</td>
<td align="right">23.0</td>
<td align="right">3.95</td>
</tr>
<tr class="even">
<td align="left">Goals scored</td>
<td align="left">Champion</td>
<td align="right">8.0</td>
<td align="right">16.92</td>
<td align="right">27.0</td>
<td align="right">5.04</td>
</tr>
<tr class="odd">
<td align="left">Losses</td>
<td align="left">Not champion</td>
<td align="right">0.0</td>
<td align="right">3.66</td>
<td align="right">8.0</td>
<td align="right">1.62</td>
</tr>
<tr class="even">
<td align="left">Losses</td>
<td align="left">Champion</td>
<td align="right">0.0</td>
<td align="right">2.23</td>
<td align="right">5.0</td>
<td align="right">1.42</td>
</tr>
<tr class="odd">
<td align="left">Performance</td>
<td align="left">Not champion</td>
<td align="right">6.7</td>
<td align="right">44.42</td>
<td align="right">83.3</td>
<td align="right">14.16</td>
</tr>
<tr class="even">
<td align="left">Performance</td>
<td align="left">Champion</td>
<td align="right">43.3</td>
<td align="right">62.82</td>
<td align="right">86.7</td>
<td align="right">12.61</td>
</tr>
<tr class="odd">
<td align="left">Points</td>
<td align="left">Not champion</td>
<td align="right">-6.0</td>
<td align="right">13.23</td>
<td align="right">25.0</td>
<td align="right">4.48</td>
</tr>
<tr class="even">
<td align="left">Points</td>
<td align="left">Champion</td>
<td align="right">13.0</td>
<td align="right">18.85</td>
<td align="right">26.0</td>
<td align="right">3.78</td>
</tr>
<tr class="odd">
<td align="left">Position</td>
<td align="left">Not champion</td>
<td align="right">1.0</td>
<td align="right">11.27</td>
<td align="right">24.0</td>
<td align="right">6.02</td>
</tr>
<tr class="even">
<td align="left">Position</td>
<td align="left">Champion</td>
<td align="right">1.0</td>
<td align="right">4.31</td>
<td align="right">11.0</td>
<td align="right">3.35</td>
</tr>
<tr class="odd">
<td align="left">Ties</td>
<td align="left">Not champion</td>
<td align="right">0.0</td>
<td align="right">2.84</td>
<td align="right">7.0</td>
<td align="right">1.31</td>
</tr>
<tr class="even">
<td align="left">Ties</td>
<td align="left">Champion</td>
<td align="right">1.0</td>
<td align="right">2.23</td>
<td align="right">5.0</td>
<td align="right">1.30</td>
</tr>
<tr class="odd">
<td align="left">Victories</td>
<td align="left">Not champion</td>
<td align="right">0.0</td>
<td align="right">3.49</td>
<td align="right">8.0</td>
<td align="right">1.51</td>
</tr>
<tr class="even">
<td align="left">Victories</td>
<td align="left">Champion</td>
<td align="right">3.0</td>
<td align="right">5.54</td>
<td align="right">8.0</td>
<td align="right">1.39</td>
</tr>
</tbody>
</table>
<p>In the 10th round we can see that the champions scored at least 8 goals, conceded at least 3 goals and lose 5 games at the most. We can see also that all the champions have woned at least 3 games, and drawn between one and five games, with the minimum performance (points made / possible points) of 43.3%.</p>
</div>
</div>
<div id="how-many-rounds-on-top-make-a-champion" class="section level2">
<h2>How many rounds on top make a champion?</h2>
<p>So, to answer my dad’s question about the football champions I thought that discovery the numbers of rounds in the first place would be of great value.</p>
<ul>
<li>Thus now we need to count the number of rounds in first place of each team in each season (year).</li>
</ul>
<pre class="r"><code>games %&gt;%
  group_by(Year,Team)%&gt;%
  #Counting the number of rounds on top
  summarise(Rounds_on_top = sum(First_place))%&gt;%
  inner_join(champ_dt)%&gt;%
  #Was this team the champion of the season?
  mutate(Won = (Team==Champion),
         Won = as.numeric(Won),
         N_round = case_when(Year &lt; 2005 ~ 46,
                             Year == 2005 ~ 42,
                             Year &gt; 2005 ~38)) -&gt; first_place_df</code></pre>
<ul>
<li>We can now calcule the proportions of rounds needed.</li>
</ul>
<pre class="r"><code>first_place_df%&gt;%
  mutate(Proportion = Rounds_on_top/N_round,
         Won = factor(Won,labels = c(&quot;Not champion&quot;,
                                 &quot;Champion&quot;)))%&gt;%
  ggplot(aes(Proportion))+
  geom_histogram(bins = 5,col=1,alpha=.5)+
  facet_wrap(~Won,scales = &quot;free_y&quot;)+
  theme_light()</code></pre>
<p><img src="/post/2019-04-24-how-many-rounds-on-top-to-glory_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>first_place_df%&gt;%
  mutate(Proportion = Rounds_on_top/N_round,
         Won = factor(Won,labels = c(&quot;Not champion&quot;,
                                 &quot;Champion&quot;)))%&gt;%
  group_by(Won)%&gt;%
  summarise(min_n=min(Rounds_on_top) %&gt;% round(digits = 2),
            mean_n = mean(Rounds_on_top) %&gt;% round(digits = 2),
            max_n=max(Rounds_on_top) %&gt;% round(digits = 2),
            min_prop=min(Proportion) %&gt;% percent(),
            mean_prop = mean(Proportion) %&gt;% percent(),
            max_prop=max(Proportion) %&gt;% percent())%&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Won</th>
<th align="right">min_n</th>
<th align="right">mean_n</th>
<th align="right">max_n</th>
<th align="left">min_prop</th>
<th align="left">mean_prop</th>
<th align="left">max_prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Not champion</td>
<td align="right">0</td>
<td align="right">0.89</td>
<td align="right">17</td>
<td align="left">0%</td>
<td align="left">2.27%</td>
<td align="left">44.7%</td>
</tr>
<tr class="even">
<td align="left">Champion</td>
<td align="right">2</td>
<td align="right">22.38</td>
<td align="right">38</td>
<td align="left">5.26%</td>
<td align="left">56.4%</td>
<td align="left">86.8%</td>
</tr>
</tbody>
</table>
<ul>
<li>So, we can note that the minimum number of rounds on top was 2 (Flamengo, 2009), while the maximum number was 38 (Cruzeiro, 2003) and the average was about 22 games. Looking on the proportions, we can see that the champions often stays on the top a bit more than half of the championship (56,4%).</li>
</ul>
<div id="estimating-the-number-of-rounds" class="section level3">
<h3>Estimating the number of rounds</h3>
<ul>
<li>To estimate the number of rounds, we can consider a logist regression with “champion” (binary) as the response variable and the proportion of rounds on first as the predictor variable.</li>
</ul>
<pre class="r"><code>first_place_df%&lt;&gt;%
  mutate(Proportion = Rounds_on_top/N_round)

#fitting the model

fit=glm(Won ~ Proportion,
        family = binomial(link = &quot;logit&quot;),
        data=first_place_df)

summary(fit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Won ~ Proportion, family = binomial(link = &quot;logit&quot;), 
##     data = first_place_df)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -1.30508  -0.08386  -0.08386  -0.08386   3.14843  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -5.6485     0.9264  -6.097 1.08e-09 ***
## Proportion   13.2860     2.5762   5.157 2.51e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 104.234  on 269  degrees of freedom
## Residual deviance:  28.442  on 268  degrees of freedom
## AIC: 32.442
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<p>Obviously the proportion of rounds in first is a important variable to explain the win. Let’s take a look in the ROC curve.</p>
<pre class="r"><code>(ROC = roc(Won ~ Proportion,data=first_place_df,percent=T))</code></pre>
<pre><code>## 
## Call:
## roc.formula(formula = Won ~ Proportion, data = first_place_df,     percent = T)
## 
## Data: Proportion in 257 controls (Won 0) &lt; 13 cases (Won 1).
## Area under the curve: 98.59%</code></pre>
<pre class="r"><code>ggroc(ROC)+
  theme_light()</code></pre>
<p><img src="/post/2019-04-24-how-many-rounds-on-top-to-glory_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<ul>
<li>We got 98.59% of Area under the curve (which is excellent). Now we can look on the true positive ratio and true negative ratio to decide a cut point.</li>
</ul>
<pre class="r"><code>data_frame(Proportion = ROC$thresholds,
           Sens = ROC$sensitivities %&gt;% round(digits = 2),
           Speci = ROC$specificities %&gt;% round(digits = 2))%&gt;%
  mutate(Proportion = percent(Proportion))%&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Proportion</th>
<th align="right">Sens</th>
<th align="right">Speci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">-Inf</td>
<td align="right">100.00</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">1.1%</td>
<td align="right">100.00</td>
<td align="right">77.04</td>
</tr>
<tr class="odd">
<td align="left">2.3%</td>
<td align="right">100.00</td>
<td align="right">78.21</td>
</tr>
<tr class="even">
<td align="left">2.5%</td>
<td align="right">100.00</td>
<td align="right">79.38</td>
</tr>
<tr class="odd">
<td align="left">3.5%</td>
<td align="right">100.00</td>
<td align="right">84.44</td>
</tr>
<tr class="even">
<td align="left">4.6%</td>
<td align="right">100.00</td>
<td align="right">85.21</td>
</tr>
<tr class="odd">
<td align="left">5.0%</td>
<td align="right">100.00</td>
<td align="right">85.60</td>
</tr>
<tr class="even">
<td align="left">5.9%</td>
<td align="right">92.31</td>
<td align="right">89.49</td>
</tr>
<tr class="odd">
<td align="left">7.2%</td>
<td align="right">92.31</td>
<td align="right">90.66</td>
</tr>
<tr class="even">
<td align="left">8.3%</td>
<td align="right">92.31</td>
<td align="right">92.61</td>
</tr>
<tr class="odd">
<td align="left">9.1%</td>
<td align="right">92.31</td>
<td align="right">93.00</td>
</tr>
<tr class="even">
<td align="left">10.0%</td>
<td align="right">92.31</td>
<td align="right">93.39</td>
</tr>
<tr class="odd">
<td align="left">10.7%</td>
<td align="right">92.31</td>
<td align="right">94.16</td>
</tr>
<tr class="even">
<td align="left">12.0%</td>
<td align="right">92.31</td>
<td align="right">94.55</td>
</tr>
<tr class="odd">
<td align="left">14.5%</td>
<td align="right">92.31</td>
<td align="right">94.94</td>
</tr>
<tr class="even">
<td align="left">17.1%</td>
<td align="right">84.62</td>
<td align="right">95.72</td>
</tr>
<tr class="odd">
<td align="left">18.7%</td>
<td align="right">84.62</td>
<td align="right">96.50</td>
</tr>
<tr class="even">
<td align="left">20.1%</td>
<td align="right">84.62</td>
<td align="right">96.89</td>
</tr>
<tr class="odd">
<td align="left">21.4%</td>
<td align="right">84.62</td>
<td align="right">97.28</td>
</tr>
<tr class="even">
<td align="left">24.0%</td>
<td align="right">84.62</td>
<td align="right">97.67</td>
</tr>
<tr class="odd">
<td align="left">27.6%</td>
<td align="right">84.62</td>
<td align="right">98.05</td>
</tr>
<tr class="even">
<td align="left">30.3%</td>
<td align="right">84.62</td>
<td align="right">98.44</td>
</tr>
<tr class="odd">
<td align="left">35.5%</td>
<td align="right">84.62</td>
<td align="right">98.83</td>
</tr>
<tr class="even">
<td align="left">41.5%</td>
<td align="right">84.62</td>
<td align="right">99.22</td>
</tr>
<tr class="odd">
<td align="left">44.1%</td>
<td align="right">76.92</td>
<td align="right">99.22</td>
</tr>
<tr class="even">
<td align="left">51.3%</td>
<td align="right">69.23</td>
<td align="right">100.00</td>
</tr>
<tr class="odd">
<td align="left">59.2%</td>
<td align="right">53.85</td>
<td align="right">100.00</td>
</tr>
<tr class="even">
<td align="left">61.2%</td>
<td align="right">46.15</td>
<td align="right">100.00</td>
</tr>
<tr class="odd">
<td align="left">66.5%</td>
<td align="right">38.46</td>
<td align="right">100.00</td>
</tr>
<tr class="even">
<td align="left">72.4%</td>
<td align="right">23.08</td>
<td align="right">100.00</td>
</tr>
<tr class="odd">
<td align="left">78.1%</td>
<td align="right">15.38</td>
<td align="right">100.00</td>
</tr>
<tr class="even">
<td align="left">84.7%</td>
<td align="right">7.69</td>
<td align="right">100.00</td>
</tr>
<tr class="odd">
<td align="left">Inf</td>
<td align="right">0.00</td>
<td align="right">100.00</td>
</tr>
</tbody>
</table>
<p>Seems like 41,5% is an good cut point because we got 99,22% of specifity (probability of classify the true champion as champion) without losing so much sensibility.</p>
<p>So let’s take a look on the model results…</p>
<pre class="r"><code>data_frame(Proportion=seq(0,1,by=.05),
           prob=predict(fit,
                        newdata = data_frame(Proportion=seq(0,1,by=.05)),
                        type = &quot;response&quot;)
)%&gt;%
  mutate(prob = percent(prob))%&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">Proportion</th>
<th align="left">prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.00</td>
<td align="left">0.4%</td>
</tr>
<tr class="even">
<td align="right">0.05</td>
<td align="left">0.7%</td>
</tr>
<tr class="odd">
<td align="right">0.10</td>
<td align="left">1.3%</td>
</tr>
<tr class="even">
<td align="right">0.15</td>
<td align="left">2.5%</td>
</tr>
<tr class="odd">
<td align="right">0.20</td>
<td align="left">4.8%</td>
</tr>
<tr class="even">
<td align="right">0.25</td>
<td align="left">8.9%</td>
</tr>
<tr class="odd">
<td align="right">0.30</td>
<td align="left">15.9%</td>
</tr>
<tr class="even">
<td align="right">0.35</td>
<td align="left">26.9%</td>
</tr>
<tr class="odd">
<td align="right">0.40</td>
<td align="left">41.7%</td>
</tr>
<tr class="even">
<td align="right">0.45</td>
<td align="left">58.2%</td>
</tr>
<tr class="odd">
<td align="right">0.50</td>
<td align="left">73.0%</td>
</tr>
<tr class="even">
<td align="right">0.55</td>
<td align="left">84.0%</td>
</tr>
<tr class="odd">
<td align="right">0.60</td>
<td align="left">91.1%</td>
</tr>
<tr class="even">
<td align="right">0.65</td>
<td align="left">95.2%</td>
</tr>
<tr class="odd">
<td align="right">0.70</td>
<td align="left">97.5%</td>
</tr>
<tr class="even">
<td align="right">0.75</td>
<td align="left">98.7%</td>
</tr>
<tr class="odd">
<td align="right">0.80</td>
<td align="left">99.3%</td>
</tr>
<tr class="even">
<td align="right">0.85</td>
<td align="left">99.6%</td>
</tr>
<tr class="odd">
<td align="right">0.90</td>
<td align="left">99.8%</td>
</tr>
<tr class="even">
<td align="right">0.95</td>
<td align="left">99.9%</td>
</tr>
<tr class="odd">
<td align="right">1.00</td>
<td align="left">100.0%</td>
</tr>
</tbody>
</table>
<p>Finnaly I can answer to my dad what is the estimated probability of a team be the champion based on how many rounds it was in the first place!</p>
</div>
</div>
